env:
  DOCKER_IMAGE_NAME: simple-bank-api
  DOCKERHUB_REPONAME: cypher00000

name: Test then Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:

  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: bdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U test" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -cover ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Short SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPONAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.SHORT_SHA }}
            ${{ env.DOCKERHUB_REPONAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPONAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPONAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
